### ISSUE TITLE
Allow to delete users via api

### ISSUE THREAD

**Issue by funkyboy** [baasbox/baasbox#149]

**Comment by fblumenberg** [comment]
Any plans to implement this in the near future?

**Comment by giastfader** [comment]
Now that we have server side scripting it will be more simple than before to implement this feature.
We can develop a raw delete user feature with a standard policy on what should happen to their own contents. Given the basic building blocks, anyone can override the default behavior.

**Comment by juliojimenez** [comment]
+1

**Comment by nlubello** [comment]
+1

**Comment by soukron** [comment]
+1 here. That would be such a nice feature.

**Comment by Alexintosh** [comment]
Will this ever happen? It's a 2 years old feature

**Comment by meeximum** [comment]
+1

**Comment by giastfader** [comment]
ok guys, we will work on it

**Comment by giastfader** [comment]
Fixed long time ago
