### ISSUE TITLE
Enable gzip encoding

### ISSUE THREAD

**Issue by zoltanf** [baasbox/baasbox#327]
It would be really usefull to enable gzip for outputs as json is a real good candidate for compression, and baasbox is mostly used from mobile devices where every byte counts...

Idealy this would be a setting that we can turn on or off as needed, per baasbox instance.

Play framework has some support for this (Thanks Claudio for this reference):
http://www.playframework.com/documentation/2.2.x/GzipEncoding

**Comment by giastfader** [comment]
to receive  a GZip encoded response, use the header:
Accept-Encoding: gzip
