### ISSUE TITLE
Allow to set ACL when creating/updating a document

### ISSUE THREAD

**Issue by funkyboy** [baasbox/baasbox#344]
Creating a document and granting permissions are two separate HTTP calls now.
It would be **very** nice to allow creating a document and granting permissions in the same HTTP call. Assets already support this.

**Comment by jouerose** [comment]
Hi Baasbox, 

Could you please implement this in the SDKs ?

**Comment by eliantor** [comment]
This is actually possible in the Android SDK:

https://github.com/baasbox/Android-SDK/blob/master/library/src/main/java/com/baasbox/android/BaasDocument.java#L572

**Comment by jouerose** [comment]
It would be great to have it in iOS too. cheers
