### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by craigphume** [baasbox/baasbox#487]
I was asked to test BAASBOX for my company as a replacement for Parse for a large project we are developing.
I ran into a few problems.

During testing we encountered a few problems, I followed the Linux guide to install and run.
We tested with 3 iPhones sending data over wifi and the iOS Simulator over wire.
The test ran for about 20 hours over night. When I returned the machine was at about 125% memory usage, and of cause lots of swapping.

In the console I had the following errors:
2014-09-23 21:50:18,088 - [error] - application: play-internal-execution-context-27 INTERNAL SERVER ERROR: POST POST /document/memos 
2014-09-23 21:50:18,090 - [error] - application: play-internal-execution-context-27 @6jj32fnaf: Execution exception in null:null

Also the throughput was very slow, with the 4 devices active it was between 130 - 300kbps.

I can supply any more information, and I can re-run the test and save the logs.

Machine Specs as follows:
HW: Mac Pro5,1
OS: Ubuntu 14.04 64bit
MEM: 4X2GB DDR3 1066MHZ
CPU: 4XIntel Xeon 2.80GHz Hyper Threading enabled
HDD: 1TB Total, 891G Free
JVM: java version "1.7.0_67"
         Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
         Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

Thanks Craig

**Comment by giastfader** [comment]
Should be resolved by updates done in https://github.com/baasbox/baasbox/tree/opti

**Comment by giastfader** [comment]
Fixed in #649
