### ISSUE TITLE
Add rating/favorite/comment API

### ISSUE THREAD

**Issue by giastfader** [baasbox/baasbox#535]
This is a very common use case: 

let's say we have documents (or files). In a social scenario users could vote or leave a public or private comment on that objects.

Working with links is possible but a low-level db design knowledge is required to realize this use case. So it should be useful to have some high-level API to manage these cases

**Comment by avently** [comment]
what does that mean "ad-hoc plugin"?

**Comment by giastfader** [comment]
it means that there is no need, at the moment, to implement this feature as a core function embedded into the BaasBox core.
It can be developed using the plugin script engine.
