### ISSUE TITLE
Hang on "Loading" spinner for non-admin login

### ISSUE THREAD

**Issue by verrol** [baasbox/baasbox#579]
If I log in as a user who is NOT admin, the main content area doesn't load. There is a "loading" spinner that remains. Clicking on the side menu doesn't nothing. The only side menu item that works is users. Which is strange, since a non-admin user shouldn't even be able to use that menu item. The result is empty, but why show it?

**Comment by giastfader** [comment]
Now only users belonging to "administrator" role can login into the Console, not even users belonging to roles that inherit administrator
