### ISSUE TITLE
Saving document with plugin

### ISSUE THREAD

**Issue by urbanL** [baasbox/baasbox#590]
This thing happens:
I have a collection named testuser@testt
And I have this sidescript
```javascript
    .post(function (req) {
        var data = req.body.data;
        var collection = req.body.collection;
        Box.log(data);
        Box.runAsAdmin(function () {
            Box.log(data);
            Box.Documents.save(collection, data);
        });
    })
```
For example data is: 
	
```
{ "cname": "Some data" }
```
And is logged as such at both log points and saving to database is successfull, but what ends up in database is:
```
{ "testt@cname": "Some data" }
```
*Note: This only happens for first element in JSON object.

Is this a bug and if it is does any of the authors know the reason behind it? If it isn't a bug what are limitiations to Collection names?

Regards.

**Comment by giastfader** [comment]
Hi, 
General rule for collection names is that they cannot start with a digit, an underscore or a @ character. 

Can you provide the entire JSON payload you send, please? 

Thanks

**Comment by urbanL** [comment]
Hi,
request is below

{"method":"POST","path":"","body":{"data":{"cname":"Some Data"},"collection":"testuser@testt"},"queryString":{},"headers":{"X-BAASBOX-APPCODE":["1234567890"],"Connection":["Keep-Alive"],"Content-Length":["58"],"X-BB-SESSION":["e55d490e-ebd4-49a1-9ef6-5f2607eefd6b"],"Content-Type":["application/json;charset=UTF-8"],"Accept-Encoding":["gzip"],"User-Agent":["BaasBox AndroidSDK/0.9.0"],"Host":["mydomain.com:9000"]}}

and results in
Collection: testuser@testt
```
{
  "testt@cname": "Some Data"
}
```

**Comment by giastfader** [comment]
I think you found a bug. As the matter of fact I am able to reproduce it even with a REST API call.

**Comment by giastfader** [comment]
Even worse, I verified that a raw insert into OrientDB causes the same problem.
I opened an issue on OrientDB: https://github.com/orientechnologies/orientdb/issues/3340

**Comment by giastfader** [comment]
In the meantime, avoid to use the @ into collection names.
On our side we can prevent the creation of collection with the @ so to avoid further problems, at least as far the OrientDB team addresses this problem.

**Comment by urbanL** [comment]
Thanks for the information will remove, will change my collection naming accordingly.

**Comment by giastfader** [comment]
Now only collection names that match the following regex are allowed:
(?i)^[A-Z-][A-Z0-9_-]*$
