### ISSUE TITLE
Support for Anonymous users

### ISSUE THREAD

**Issue by dirkam** [baasbox/baasbox#596]
It'd be great to have some kind of support for Anonymous users. Upon initialization if the user has not been registered, BaasBox could create some kind of user credentials to access the resources. This would be useful in many cases such as if the user wants to try the app first without registering. Obviously some of the feature would not be supported (such as accessing the same user's data from another device or the friendship social api).
It would be necessary to link/merge the user accounts if the user decides to register.

There are some MBaaS providers, which support this.

**Comment by giastfader** [comment]
What about the "change username" feature?
I mean, the app could create a fake user with a fake username/password when it starts.
Now, form the server perspective, this is a registered user.
If the user decides to register, he/she provides a valid username/password pair and then the app could call the "change username" and "change passoword" functions.

**Comment by dirkam** [comment]
Sounds good, what if the user logs in with a social account?

**Comment by giastfader** [comment]
Yes, we are thinking about it.
We have to  implement this first #605 
(the 5th point)
