### ISSUE TITLE
Alternative ways for Authorization 

### ISSUE THREAD

**Issue by mehdi-cit** [baasbox/baasbox#610]
Hello!
Baasbax seems interesting but I find the documentation lacking. It's not clear what's possible and what's not!
In the latest video http://vimeo.com/110270602 
We can see what looks like taking advantage of some 'install' "event":
on('install', function(){
// do magic here
});
But I wasn't able to find the available "events". I's particularly interested in checking whether I can hook up into Baasbox internals so as to hijack crud access to some collection. If that was possible one would be able to implement custom authorization in code. Let's say if the user requests lacks some specific token write access would be denied whereas read access is universally allowed.
If such thing was possible one could have a parallel authentication mechanism ( totally independent from Baasbox) and let that mechanism provide authenticated users/devices with some JWT token.
On baasbox's "on document XYZ access event" one verifies the token to either grant or deny access.

**Comment by eliantor** [comment]
Currently the only managed event, is 'install'.
The on() function is designed to hook on plugin lifecycle events.
We plan to add other BaasBox internal hooks on collections etc... , through other mechanics.

**Comment by mehdi-cit** [comment]
Thank you for the reply.
Any timeline, road map`?
It does not need be precise just to have an idea!
