### ISSUE TITLE
askToEnablePushNotifications issue with iphone5 v8.0

### ISSUE THREAD

**Issue by kottle** [baasbox/baasbox#630]
I've found a possible issue in your baasbox library (object-c) v0.8.4
It seems the issue is due to a bad firmware detection of your library, I've a smartphone with version 8.0 but it has been recognized as v 7.0.
This causes a bad configuration so that the device is not ready to get notifications...
I appended a log and your code:

2015-01-13 22:24:28.364 XXXXXX[3737:1834205] VERSION:70000
- (void) askToEnablePushNotifications {

#if TARGET_OS_IPHONE
    NSLog(@"VERSION:%d", __IPHONE_OS_VERSION_MIN_REQUIRED);
    #if __IPHONE_OS_VERSION_MIN_REQUIRED  >= 80000
        UIUserNotificationSettings *settings =[UIUserNotificationSettings settingsForTypes:UIUserNotificationTypeAlert |UIUserNotificationTypeBadge |  UIUserNotificationTypeSound  categories:nil];
        [[UIApplication sharedApplication] registerUserNotificationSettings:settings];
        [[UIApplication sharedApplication] registerForRemoteNotifications]
    #else
        [[UIApplication sharedApplication] registerForRemoteNotificationTypes:(UIRemoteNotificationTypeBadge | UIRemoteNotificationTypeSound | UIRemoteNotificationTypeAlert)];
    #endif 
#else
    [[NSApplication sharedApplication] registerForRemoteNotificationTypes:(NSRemoteNotificationTypeBadge | NSRemoteNotificationTypeSound | NSRemoteNotificationTypeAlert)];
#endif
}

I suggest to you this code instead:
// Register for Push Notitications, if running iOS 8

    if ([application respondsToSelector:@selector(registerUserNotificationSettings:)])

    {

        UIUserNotificationType userNotificationTypes = (UIUserNotificationTypeAlert |

                                                        UIUserNotificationTypeBadge |

                                                        UIUserNotificationTypeSound);

        UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:userNotificationTypes

                                                                                 categories:nil];

        [application registerUserNotificationSettings:settings];

        [application registerForRemoteNotifications];

    } else {

        // Register for Push Notifications before iOS 8

        [application registerForRemoteNotificationTypes:(UIRemoteNotificationTypeBadge |

                                                         UIRemoteNotificationTypeAlert |

                                                         UIRemoteNotificationTypeSound)];

    }

Ciao
Elio

**Comment by funkyboy** [comment]
This should have been fixed with release 0.9. Let us know (and feel free to reopen) if not.
