### ISSUE TITLE
Admin Console error accessing Documents when using Reverse Proxy

### ISSUE THREAD

**Issue by gsdatta** [baasbox/baasbox#643]
I've set up a simple reverse proxy on localhost using nginx, listening on https://localhost:443. I changed the corresponding port config setting in BaasBox's settings panel.

When attempting to access Documents, the console does not work because the API request is using absoluteURL(). For some reason, the call is going to https://localhost:9000/document/<collection> (rather than https://localhost:443, or at least http://localhost:9000). This is occurring even though network.http.url and network.http.ssl are all set correctly. A have used a temporary fix for this that generates a URL based on window.location.origin and the relative URL of the call. The smarter thing to do would be to use the config files and generate the URL based on that.

**Comment by giastfader** [comment]
fixed by https://github.com/baasbox/baasbox/pull/644
