### ISSUE TITLE
Box.WS.get(); should allow specifying a custom time-out

### ISSUE THREAD

**Issue by raffael** [baasbox/baasbox#655]
In BaasBox plug-ins you can send HTTP requests to 3rd party web services via

```
    Box.WS.get(url,{params:{ ... }});
```

Currently, it seems like the time-out for these requests is set to 3 seconds, and there is no option to specify a custom time-out. Thus, requests to 3rd party APIs that take longer than 3 seconds cannot be made currently:

```
    "error":"exec","errorCode":1,"command":{"resource":"script","name":"ws", [...]
    "message":"Futures timed out after [3000 milliseconds]"}
```

**Comment by giastfader** [comment]
Try to use the ws.timeout (in ms) parameter in command line:
````
./start -Dws.timeout=120000
````

**Comment by raffael** [comment]
Thanks for the swift reply! So I just tried that (OS X):
```
    ./start -Dws.timeout=120000
```

I'm still getting the timeout after 3 seconds. I just googled the Play framework starting configuration parameters, and it does seem to be ```ws.timeout``` in fact, however it seems to be ignored by BaasBox?

**Comment by giastfader** [comment]
Yes, sorry, silly me.
We set that value and cannot be overridden at the moment

**Comment by raffael** [comment]
okay :) Yeah, a simple additional parameter would be great:

```
{
    params: { … },
    timeout: 10000,
}
```

**Comment by giastfader** [comment]
Now you have the timeout (in ms) parameter.
Example:
````Javascript
    var result=Box.WS.get("http://validate.jsontest.com",
                        {
                            params:{
                                json:'{"k2":"v"}'
                            },
                            timeout:10000
                        });
});
````
The default value is 5000ms and can be override via conf file or passed to the _start_ script.
If the remote server does not end the connection within the specified timeout, an exception is raised by the engine.

Other predefined timeouts are (see https://www.playframework.com/documentation/2.2.x/ScalaWS#Timeouts)
````
ws.timeout.connection=5000 #The maximum time to wait when connecting to the remote host
ws.timeout.idle=10000 #The maximum time the request can stay idle (connection is established but waiting for more data)
````
They can only be overridden at startup time (_conf_ or _start_)

Additionally the returned object now has the _execution_time_ field: if everything went ok, it contains the time taken to perform the operation (in ms).
The previous call will returns something similar to:
````Javascript
{
    "status": 200,
    "execution_time": 190,
    "body": {
      "object_or_array": "object",
      "empty": false,
      "parse_time_nanoseconds": 22938,
      "validate": true,
      "size": 1
    }
````
