### ISSUE TITLE
Parameters seem to be ignored while querying the DB in plug-ins.

### ISSUE THREAD

**Issue by raffael** [baasbox/baasbox#656]
Whenever I am querying the database to fetch links or documents, the specified ```params``` seem to be ignored:

```
    var labelName = 'bought',
        objectId = 'someId';
    var linkedTopics = Box.Links.find({
            where: "label=? AND out.id=?",
            params: [labelName, objectId]
    });
```

Encapsulating the question marks in quotes doesn't help either:

```
            where: "label=? AND out.id=?",
```

Result: I am not getting any query results from the database. However, if I insert the respective variables into the string, everything is working fine:

```
            where: "label='?' AND out.id='" + objectId + "'",
```

Same behavior for ```Box.Documents.find()```.
Am I using the question marks incorrectly?

(v0.9.2)

**Comment by nareninindia** [comment]
Hi

Based on documentation of pluginApi, the syntax is

var labelName = 'bought';
        objectId = 'someId';
    var linkedTopics = Box.Links.find({
            where: "label=labelName AND id=objectId"
    });

**Comment by raffael** [comment]
@nareninindia 

No, the question marks [should] act as placeholders for the variables you provide with the ```params:``` value:

```
    var links=Box.Links.find({
           where:"label='invoiceItem' and out.id=?",
           params:[invoiceId]
       });
```

**Comment by nareninindia** [comment]
:) Digged into the code further. There is support for params. Better people from Baasbox answer this :)
Hope they add this into the documentation too..

**Comment by giastfader** [comment]
ok, I found a problem with the bridge javascript/java that happens when a param is an array.
As a workaround, at the moment, if you have just one value in your selection criteria, avoid to use arrays.
In other words:
````
    var links=Box.Links.find({
           where:"label='invoiceItem' and out.id=?",
           params:invoiceId
       });
````
Please try and let me know

**Comment by giastfader** [comment]
The problem is that the values within the array come to the Java code wrapped within quotes.
For example:
[1,2,3]
become
["1","2","3"]
as the quotes were part of the values. This is the reason why the queries fail.
