### ISSUE TITLE
User was online...when?

### ISSUE THREAD

**Issue by avently** [baasbox/baasbox#659]
Hello. I can't find an option to see the user's last active date. Date of profile creation is here, yes, but what to do if i need to show when user was online?

**Comment by raffael** [comment]
If BaasBox doesn't provide it out of the box, you probably should do it on your own: Everytime the user logs on in your app, save a ```lastActivity``` timestamp / date in the ```visibleForRegisteredUsers``` dictionary of the user object. Then save it.
