### ISSUE TITLE
Use User_id or link instead of Username

### ISSUE THREAD

**Issue by avently** [baasbox/baasbox#661]
Sometimes in Documents we need to make a link to one or many users. For example, chat message has a sender user (_author_id of Document) and a receiver of the message (another User or many users). Cool, but how I can do that? I will make an array of receivers with their Usernames and save it in the Document field. And once user will want to change his Username he lose all of his privileges to find Document that linked on him. He can't find messages, reviews and other cool features I gave him. 

If I could use something like user_id it would give me a result I want. 
Another option is links. Something like @Username. When developer use in Documents symbol "@" before one word means that he make a link on user. And when this user want to change his username baasbox trying to find all occurrences of @Username and replace it with new value. 

What do you think about it?

**Comment by EdwardSeshoka** [comment]
Were you able to link users to documents?

**Comment by avently** [comment]
No, I don't. When user will change username I'll just find all occurrences of his username and replace it with new value. But now this method also doesn't work because I don't have an access to db. It will be fixed soon and I don't worry. 

If you want to link user you can make it with orientdb link field or link list, list map etc. You should paste user RID into a document field. You can find user RID when querying for users. It located at _BB_Users class.
