### ISSUE TITLE
[Links] Ability to link users to documents or files.

### ISSUE THREAD

**Issue by Zeraceee** [baasbox/baasbox#676]
Baasbox can be a pain to store information with, because all information is overwritten on a PUT request. This makes things really complicated when you want to add new data to a user object. Links are a great relational model, and can link documents and files. However, links currently can't link a username to a file or document.

This feature would be really useful for creating relationships between users and documents without suffering through many issues with saving user objects. It turns 20+ lines of code into one for us users.

Please consider allowing links between users and objects or files.

**Comment by funkyboy** [comment]
+1.

**Comment by giastfader** [comment]
Link users and documents is a cool feature that we will implement.
However, as far as documents are concerned, you can update just a single field, without sending the entire document.
This feature is not available on users' profile.

Please see: http://www.baasbox.com/documentation/#update-a-document-39-s-field

**Comment by Zeraceee** [comment]
@giastfader I am aware. Currently, for creating links between users and docs, however, I must overwrite every detail of the user or take the user's previous json object for 'visibileByFriends' and then modify it. This is extremely annoying in JS. with a link, life would be easier.

One workaround is creating an object per user and linking those two via object the objects ID at signup, then linking the object to other objects (first object acts as linkable user). This is just really cumbersome compared to simply linking a user with an object.

**Comment by EdwardSeshoka** [comment]
+1. @Zeraceee I was also thinking of a way to link users with documents, and thought of your workaround, have you been able to implement it? How successful is it?

**Comment by giastfader** [comment]
To link users with objects with have to expose the users' id.
My only concerns are about possibile security issues that could come from this.
We have to think about it.
As far as the workaround is concerned it is very simple. 
+ Create a collection with a name as linkable_users 
+ Anytime a new user signs up, create a document in this collection giving  permissions to no one else. 
+ Put (just once) the id of the document into the private section of the user profile
+ Now you can use this document to link any other link or file

**Comment by avently** [comment]
@giastfader, why not just allow all to link users with files? Users and
documents are the same - classes in orientdb. So what's a difference
between linking doc with doc and user (it's just a doc) with other doc?
Пн, 16 марта 2015 г. в 14:00, giastfader <notifications@github.com>:

**Comment by EdwardSeshoka** [comment]
@giastfader Any ETA regarding traversing links?

**Comment by giastfader** [comment]
@EdwardSeshoka as soon this issue will be closed https://github.com/baasbox/baasbox/issues/651
you will be able to perform raw OrientDB queries

**Comment by giastfader** [comment]
closed by #729
