### ISSUE TITLE
change role "registered"

### ISSUE THREAD

**Issue by ffnoname** [baasbox/baasbox#680]
I have implicit registration in my app. A user starts it and gets registered with a random username. When he now actively decides to register, I change the username, password AND the role (to a role called "selfregistered").
but the user with the new role can still access all documents that have only permissions granted for role "registered". even new documents that are created after the role was changed. Is there some kind of inheritance in the roles and "registered" is a "base role" that all other self defined roles inherit? Or is the new role only added and the user is now in role "registered" and "selfregistered"? When querying these users the response shows only the "selfregistered" role.
Is that supposed to be like that or am I missing something?

**Comment by funkyboy** [comment]
Registered is "every user with an account".

**Comment by ffnoname** [comment]
yepp that´s fine. thanks for the clarification
