### ISSUE TITLE
Allow to disable read, update and delete to document _author

### ISSUE THREAD

**Issue by avently** [baasbox/baasbox#681]
Hello. I'm creating a chat and in some situations i want to disable access to document's creator but Baasbox doesn't allow it. For example:

Box.runAsAdmin(function(){
Box.Documents.revoke("Dialogs",dialog_id,
            {
                users: {
                   all:username //this is username of the _author
                }
            });

```
});
```

In this situation _author CAN read document and do what he want. My job is to hide this document from him because it's dialog wants user to delete. i just drop his "read" permission and other chat opponents will have access to this dialog.

Please, give us this kind of functionality.

**Comment by giastfader** [comment]
That code should revoke the ownership of the document.
Are you sure you did not grant to the author the READ permission too?
Removing from the ALL permission does not mean that he is implicitly removed from other permissions too.
Please check also for roles. If the author belongs to a role that has the READ permission on that document, then that user can still see it.
And, finally, the users belonging to the administrator role have alway full access to all docs, files, and users' profile.

**Comment by avently** [comment]
Here is another example. It should work but it doesn't. Is it my fault? I'm new in Javascript:) The user has a registered role. 

var newMessage = Box.Documents.save("Messages",
    {
      "message": message,
      "type":"standart",
      "files":files,
      "read" : []
    });
    
    Box.Documents.grant("Messages",newMessage.id,
            {
                users: {
                   read: [receiver],  // not the _author
                   update : [],  //i also tried "write"
                   delete : []
                }
            });
            
            Box.Documents.revoke("Messages",newMessage.id,
            {
                users: {
                   read: [me.user.name],  // _author
                   update :[me.user.name],  //i also tried "write"
                   delete : [me.user.name]
                }
            });

**Comment by funkyboy** [comment]
Should be `read: ["receiver"], with quotes, because a username is a string.

**Comment by avently** [comment]
Receiver is a variable. 

var receiver = "someuser";

read: [receiver];

**Comment by giastfader** [comment]
Ok, to revoke all kind of permission to the author, try:
```
  Box.Documents.revoke("Messages",newMessage.id,
        {
            users: {
               read: [me.user.name],  // _author
               update :[me.user.name], 
               write:[me.user.name], //due #682
               delete : [me.user.name],
               all:[me.user.name] //  <<<----- the owner by default is here
            }
        });
```

**Comment by EdwardSeshoka** [comment]
Hi guys, how do I make sure all documents in a collection are publicly accessible by every user, of do I have to grant permissions for users 1 by 1?
