### ISSUE TITLE
Check if a user is already signed up by email

### ISSUE THREAD

**Issue by EdwardSeshoka** [baasbox/baasbox#685]
Is there an api that I can use to check if a user is already signed up by email, I tried loadUsersWithParameters:completion but I am not sure how to set up the where clause for the users, although passing nil for parameters returns all users.

When signing up a new user with a Facebook or Google account, I first want to check if their details exist on the server or not and if they do, be able to link the auth token to that existing account.

I am on iOS.

Regards

**Comment by funkyboy** [comment]
The query for the where clause is "username = 'john@john.com'"

**Comment by giastfader** [comment]
From v.0.9.4 emails are unique
https://github.com/baasbox/baasbox/issues/447
