### ISSUE TITLE
BaasBox v. 0.9.4-20150211 post to /admin/plugin

### ISSUE THREAD

**Issue by emresebat** [baasbox/baasbox#688]
Hi I'm posting this data to admin/plugin to create a plugin script

```javascript
{
	"name": "kasa.lib",
	"code": "var x=5;"
}
```
I always get this response:

```javascript
{
	"result": "error",
	"message": "java.lang.NullPointerException\n\tat com.baasbox.service.scripting.ScriptingService.createScript(ScriptingService.java:350)\n\tat com.baasbox.service.scripting.ScriptingService.create(ScriptingService.java:190)\n\tat com.baasbox.controllers.ScriptsAdmin.create(ScriptsAdmin.java:112)\n\tat Routes$$anonfun$routes$1$$anonfun$applyOrElse$134$$anonfun$apply$134.apply(routes_routing.scala:1767)\n\tat Routes$$anonfun$routes$1$$anonfun$applyOrElse$134$$anonfun$apply$134.apply(routes_routing.scala:1767)\n\tat play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183)\n\tat play.core.Router$Routes$$anon$1.invocation(Router.scala:377)\n\tat play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56)\n\tat play.GlobalSettings$1.call(GlobalSettings.java:64)\n\tat com.baasbox.controllers.actions.filters.ExtractQueryParameters.call(ExtractQueryParameters.java:44)\n\tat com.baasbox.controllers.actions.filters.CheckAdminRoleFilter.call(CheckAdminRoleFilter.java:51)\n\tat com.baasbox.controllers.actions.filters.ConnectToDBFilter.call(ConnectToDBFilter.java:81)\n\tat com.baasbox.controllers.actions.filters.UserCredentialWrapFilter.call(UserCredentialWrapFilter.java:74)\n\tat play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91)\n\tat play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90)\n\tat play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)\n\tat play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)\n\tat scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)\n\tat scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)\n\tat scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)\n\tat play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)\n\tat akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)\n\tat akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)\n\tat scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n",
	"resource": "/admin/plugin",
	"method": "POST",
	"request_header": {
		"X-BAASBOX-APPCODE": ["REMOVED"],
		"Content-Length": ["42"],
		"Accept": ["*/*"],
		"Content-Type": ["application/json"],
		"Authorization": ["REMOVED"],
		"User-Agent": ["curl/7.37.1"],
		"Host": ["REMOVED"]
	},
	"API_version": "0.9.4-20150211-nightly",
	"http_code": 500
}
```
I normally try to send the base64 encoded contents of my js file but the error is the same. 

Any ideas?

**Comment by giastfader** [comment]
try:
```
{
    "lang": "javascript",
    "name": "kasa.lib",
    "code": "var x=5;"
}
```

**Comment by giastfader** [comment]
We have to validate the lang field.

**Comment by emresebat** [comment]
Hi thanks for the quick reply.

This clears the NullPointerException, but still I can't send the contents of file. For valid JSON I used base64 decoded string as "code" key. But on server side it doesn't base64 decode.

So with all curly braces and quotes, how should we post javascript code?

**Comment by giastfader** [comment]
Why do you encode the code?
BaasBox wants plain javascript code in that field.

**Comment by emresebat** [comment]
Ok so if I do that like this

```javascript
{ "lang": "javascript", "name": "kasa.lib2", "code": "/**
 * Created by emresebat on 13/02/15. time 00:11
 * Updated by emresebat on 25/02/15. time 20:11
 */

var first = function (collectionName, fieldNames, whereClause) {
    var obj = Box.Documents.find(collectionName, {
        fields: fieldNames,
        where: whereClause
    });
    if (obj && obj.length > 0) {
        return obj[0];
    }
    return null;
}

//exports
exports.first = first;" }
```

I receive this response 

```javascript
{
	"result": "error",
	"message": "Invalid Json",
	"resource": "/admin/plugin",
	"method": "POST",
	"request_header": {
		"X-BAASBOX-APPCODE": ["REMOVED"],
		"Content-Length": ["455"],
		"Accept": ["*/*"],
		"Content-Type": ["application/json"],
		"Authorization": ["REMOVED"],
		"User-Agent": ["curl/7.37.1"],
		"Host": ["ec2-54-93-80-160.eu-central-1.compute.amazonaws.com:9090"]
	},
	"API_version": "0.9.4-20150211-nightly",
	"http_code": 400
}
```

Since my javascript contains new line, curly braces etc it break the json. So how should I send it?

**Comment by giastfader** [comment]
Why don't you use the Embedded Console?
It is the official way to load a script. Otherwise, of course, you need some tool to make a consistent POST request to the server.
However in some case, for example shell script to pre-load plugins in empty BaasBox(es), I agree that it can be interesting to post the code content encoded in BASE64.

**Comment by emresebat** [comment]
Embedded console works and also the code editor is pretty good.

But I keep the plugin on a repository and I want to be able post it from shell. I use IntelliJ Idea and created a bash script to post the code content. Embedded console only support copy/paste which is not enough for this workflow. 

I update the code, test it, commit to git and post it to bassbox. 

Also I think there is only option to POST, it would be great to support PUT to update the script. 

I can also share the bash script if you like to test it.

**Comment by giastfader** [comment]
Those APIs are not documented.
As the matter of fact there is a PUT endpoint (that is used by the console):
PUT  /admin/plugin/:name
(https://github.com/baasbox/baasbox/blob/0.9.2/app/com/baasbox/controllers/ScriptsAdmin.java#L84 )

It would be great if you can share your script, thanks!

**Comment by emresebat** [comment]
Aah great info :)

Here are the scripts https://gist.github.com/emresebat/7ef827ad879059357641

Now if only base64 decoding was available this would be a good solution.

**Comment by giastfader** [comment]
Ok, let's see if we can push this feature in next release
:)

**Comment by emresebat** [comment]
With your help I found a workaround :)

I've updated the scripts https://gist.github.com/emresebat/7ef827ad879059357641

So basically a single line javascript works without any problems :)
