### ISSUE TITLE
BaasBox v. 0.9.4-20150211 Box.WS.get with url with query string

### ISSUE THREAD

**Issue by emresebat** [baasbox/baasbox#690]
Hi

I'm trying to implement a basic Parse data importer plugin like this https://gist.github.com/emresebat/48d43ebd6f83ccd3f0c6

Which works but I can't send urls with query string like

https://api.parse.com/1/classes/product/?include=category&skip=1000&limit=1000

When I log the url it seems just to receive the url without querystring values. But the same url works with postman. 

Any ideas about this or should go for simple a web request implementation myself?

**Comment by giastfader** [comment]
Did you try to call the WS API as shown here: https://github.com/baasbox/baasbox/wiki/PluginApi#remote-web-services ?

Something like:
```Javascript
var result = Box.WS.get(url, {
    params: {
      include:"category",
      skip:1000,
      limit:1000
    },
    headers: getParseHeader()
});
```

**Comment by emresebat** [comment]
I'm pretty sure this was not on the documentation, was it updated recently?

Thanks for the info.

**Comment by giastfader** [comment]
No, it was there from December :)

https://github.com/baasbox/baasbox/wiki/PluginApi/e78a9cb1bff8b9b3b42568fca425d3834a0f8b99#remote-web-services

**Comment by emresebat** [comment]
Then I'm really sorry for asking this easy question. :) Must be the late hours...
