### ISSUE TITLE
Authentication invalidated if server restarts, but SDK Client reports authenticated as true

### ISSUE THREAD

**Issue by vishvish** [baasbox/baasbox#703]
Using iOS SDK, login works fine through `BAAUser` but when server is restarted and client is previously logged in, `BAAClient.isAuthenticated()` reports `true` but unable to logout. Logout attempts result with the error message, "Authentication info not valid... HINT: is your session expired?"

We have an session checker exposed through the API?

**Comment by avently** [comment]
You don't need the session checker. SDK showes always true if session token exists on device. So in your situation you need to subscribe to notification from SDK and then you will know when session will be invalid. Every call to server returns info about session. If session is invalid you will be notified. 

In next version of baasbox sessions will be permanents. So after server restart every session will work like before restart.

**Comment by vishvish** [comment]
Thanks for clarifying. Is the correct notification `BAAClient kAuthenticationTokenExpiredNotification`?

**Comment by funkyboy** [comment]
Correct.
