### ISSUE TITLE
Password Reset link not correct from ec2

### ISSUE THREAD

**Issue by EdwardSeshoka** [baasbox/baasbox#716]
Having deployed Baasbox on ec2, the password recovery link still has a localhost/9000 instead of publicdns/9000, how do I change this?

**Comment by funkyboy** [comment]
In the console: Settings/Application
Change the `network.http.url` field

**Comment by EdwardSeshoka** [comment]
Thanks, is there a reason why the server stops running after ssh? Seems I can't keep Baasbox running indefinitely it just stops at some point of if I terminate ssh.

**Comment by avently** [comment]
You should write symbol '&' after ...connect
Сб, 14 марта 2015 г. в 21:29, EdwardSeshoka <notifications@github.com>:

**Comment by EdwardSeshoka** [comment]
I did already actually, was always including that.

**Comment by bennythomps** [comment]
Try `nohup ./start &` or better yet, I'd suggest running docker in daemon mode.
