### ISSUE TITLE
Can't change admin password

### ISSUE THREAD

**Issue by tobykurien** [baasbox/baasbox#719]
I've installed a fresh copy of bassbox v0.9.2. I then logged in with the ```admin:admin``` username/password, and changed the password to a 12 character password (with special characters). After logging out, I cannot log back in. If I try to log in with the new password, it shows the invalid username/password error, and if I log in with admin as password, it immediately logs me back out with ```Sorry, session has expired``` error message.

**Comment by giastfader** [comment]
I have just tried with 1˜Ó3@5àç8912 and it worked.
Can you please provide more details?
What password did you use?

**Comment by tobykurien** [comment]
It works with your password, try with ```x9%YsydsdWER```

**Comment by giastfader** [comment]
Works for me even with yours.
I'm using Chrome, this is the call:

Request:
```
Remote Address:[::1]:9000
Request URL:http://localhost:9000/login
Request Method:POST
Status Code:200 OK

Response Headers
view source
Access-Control-Allow-Headers:X-Requested-With
Access-Control-Allow-Origin:*
Content-Encoding:gzip
Content-Length:215
Content-Type:application/json
Date:Wed, 18 Mar 2015 12:56:11 GMT
Vary:Accept-Encoding

Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,it;q=0.6
Connection:keep-alive
Content-Length:57
Content-Type:application/x-www-form-urlencoded; charset=UTF-8

Host:localhost:9000
Origin:http://localhost:9000
Referer:http://localhost:9000/console/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
X-BB-SESSION:undefined
X-Requested-With:XMLHttpRequest

Form Data
username:admin
password:x9%YsydsdWER
appcode:1234567890
```

Response:
```
{"result":"ok","data":{"user":{"roles":[{"name":"administrator","isrole":true}],"name":"admin","status":"ACTIVE"},"signUpDate":"2013-09-05T17:22:29.366+0200","generated":null,"X-BB-SESSION":"1b5b58b7-5d32-46f4-a58a-7ce777d57442"},"http_code":200}
````

Can you post more details about server response/exception?

**Comment by tobykurien** [comment]
I'm sorry I made a mistake with previous password. Try this password ```x9%YsymRuebF``` 
The JSON PUT request is: ```{"old":"x9%YsydsdWER","new":"x9%YsymRuebF"}```
Thereafter I cannot log in.

**Comment by tobykurien** [comment]
Ok, it seems not related to the password, but rather to the password manager I am using. If I paste the password in, it works, but if I use the password manager, it doesn't. So I guess it's a javascript issue, perhaps with the password being filled in without the field gaining and losing focus?

**Comment by tobykurien** [comment]
I tried now to use the password manager, then when it's done, I insert a space and remove it, then login. Then it works.
