### ISSUE TITLE
Migration problem Evolution to 0.8.4 Error

### ISSUE THREAD

**Issue by erayoezmue** [baasbox/baasbox#726]
When I want to load a Backup from an 0.8.2 version of BaasBox to a newer one, I get an error:

There was a problem processing the file: java.lang.Exception: There was an error handling your zip import file. at com.baasbox.service.dbmanager.DbManagerService.importDb(DbManagerService.java:190) at com.baasbox.controllers.Admin.importDb(Admin.java:716) at Routes$$anonfun$routes$1$$anonfun$applyOrElse$124$$anonfun$apply$124.apply(routes_routing.scala:1687) at Routes$$anonfun$routes$1$$anonfun$applyOrElse$124$$anonfun$apply$124.apply(routes_routing.scala:1687) at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) at play.GlobalSettings$1.call(GlobalSettings.java:64) at com.baasbox.controllers.actions.filters.ExtractQueryParameters.call(ExtractQueryParameters.java:44) at com.baasbox.controllers.actions.filters.CheckAdminRoleFilter.call(CheckAdminRoleFilter.java:51) at com.baasbox.controllers.actions.filters.ConnectToDBFilter.call(ConnectToDBFilter.java:81) at com.baasbox.controllers.actions.filters.UserCredentialWrapFilter.call(UserCredentialWrapFilter.java:74) at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) Caused by: com.baasbox.exception.UnableToImportDbException: Unable to import db exception at com.baasbox.db.DbHelper.importData(DbHelper.java:622) at com.baasbox.service.dbmanager.DbManagerService.importDb(DbManagerService.java:179) ... 25 more Caused by: java.lang.RuntimeException: java.lang.ClassCastException: com.orientechnologies.orient.core.record.impl.ODocument cannot be cast to com.orientechnologies.orient.core.id.ORID at com.baasbox.db.Evolution_0_8_4.evolve(Evolution_0_8_4.java:69) at com.baasbox.db.Evolutions.performEvolutions(Evolutions.java:46) at com.baasbox.db.DbHelper.evolveDB(DbHelper.java:664) at com.baasbox.db.DbHelper.importData(DbHelper.java:616) ... 26 more Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.record.impl.ODocument cannot be cast to com.orientechnologies.orient.core.id.ORID at com.baasbox.db.Evolution_0_8_4.exposeSocialId(Evolution_0_8_4.java:219) at com.baasbox.db.Evolution_0_8_4.evolve(Evolution_0_8_4.java:66) ... 29 more

The same happens when I copy the whole db folder to the new server and try to start it - it will fail.

**Comment by giastfader** [comment]
This should be fixed now. Can you try the latest snapshot, please?
