### ISSUE TITLE
Is there an API for nearby locations using Spatial Index of OrientDB?

### ISSUE THREAD

**Issue by EdwardSeshoka** [baasbox/baasbox#728]
Since we don't have full control of the OrientDB database, is there anyway I can query for locations near a certain longitude and latitude or not yet.

**Comment by giastfader** [comment]
Hi,
take a look here
http://www.baasbox.com/documentation/#how-to-query-with-the-creation-date

**Comment by swampie** [comment]
@giastfader meant http://www.baasbox.com/documentation/#geospatial-queries

**Comment by giastfader** [comment]
Yes... sorry... bad cut&paste
