### ISSUE TITLE
Direct download link for stable version

### ISSUE THREAD

**Issue by emresebat** [baasbox/baasbox#734]
Hi 

I've used this article (http://www.baasbox.com/baasbox-on-amazon-ec2/) to successfully install the nightly build to an amazon S2 instance. 

But when I try to install the 0.9.2 stable version I could not find any direct links so wget or curl does not work o the server.

Isn't there a direct link like http://www.baasbox.com/download/baasbox-0.9.2.zip ?

**Comment by giastfader** [comment]
Here is the wget command to download the latest stable release:
wget --content-disposition http://www.baasbox.com/download/baasbox-stable.zip

**Comment by emresebat** [comment]
Ahhh great, I tried like http://www.baasbox.com/download/baasbox-0.9.2.zip because of the file name from the web site.

baasbox-stable.zip makes sense of course :) 

Thanks.

**Comment by emresebat** [comment]
Just wondering the same thing for 1.0.0-M1 because I can't find it and it's no where to be found. I know you need statistics etc on the web site but we really need direct links to setup it on the servers from shell.

This does not work 
http://www.baasbox.com/download/baasbox-1.0.0-M1.zip
And
http://www.baasbox.com/download/baasbox-nightly.zip
is not the same as M1 I think.

**Comment by giastfader** [comment]
Done:
wget --content-disposition http://www.baasbox.com/download/baasbox-1.0.0-M1.zip

v1.0.0-M1 is equivalent to the 0.9.2 with many improvements on performance side.
Nightly build is the next v0.9.4. When we will release it, we will release the 1.0.0-M2 too and then the 1.0.0-final.

**Comment by emresebat** [comment]
Thank you! Just to be sure I really need the indexing support so is it available for M1 or should I go with 0.9.4 nightly?

**Comment by giastfader** [comment]
The indexes support within the console will be available in 1.0.0-M2 https://github.com/baasbox/baasbox/issues/608

In the meantime you can create an index on a collection using this code into a plugin:
````
Box.DB.exec("create property  <collection_name>.<field_to_index>  string");
Box.DB.exec("create index   <collection_name>.<field_to_index>  notunique");
```

Refs: 
http://orientdb.com/docs/1.7.8/orientdb.wiki/SQL-Create-Index.html
http://orientdb.com/docs/1.7.8/orientdb.wiki/Indexes.html

**Comment by emresebat** [comment]
Ok but for Box.DB.exec I need nightly build or 1.0.0.M1 right? 0.9.2 does not have this function.

**Comment by giastfader** [comment]
0.9.4 nightly
