### ISSUE TITLE
Alter property - nullPointerException

### ISSUE THREAD

**Issue by avently** [baasbox/baasbox#740]
I'm using this code and it looks OK and working fine via OrientDB studio, but produces Null exception in Plugins:

Box.DB.exec("create property Country.EN STRING");    //This is works
Box.DB.exec("alter property Country.EN collate ci");       //Exception

Do you know any workaround?

"result": "error",
"message": "script failure com.baasbox.service.scripting.base.ScriptEvalException: ScriptError: 'java.lang.NullPointerException' at: <<eval>>176:16\ <eval>:176:16 java.lang.NullPointerException\ \	at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:111)\ \	at jdk.nashorn.internal.scripts.Script$\\^eval\\_.L:25$Module$L:155(<eval>:176)\ \	at jdk.nashorn.internal.scripts.Script$baasbox_core.:scopeCall(baasbox.core)\ \	at jdk.nashorn.internal.scripts.Script$baasbox_core.L:134(baasbox.core:141)\ \	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:539)\ \	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)\ \	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)\ \	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:109)\ \	at jdk.nashorn.internal.scripts.Script$locations_import.L:89(locations.import:107)\ \	at jdk.nashorn.internal.scripts.Script$locations_import.L:1(locations.import:10)\ \	at jdk.nashorn.internal.scripts.Script$\\^eval\\_.L:25$ModuleRef$L:282$L:284(<eval>:288)\ \	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:537)\ \	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)\ \	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)\ \	at jdk.nashorn.internal.objects.NativeFunction.apply(NativeFunction.java:130)\ \	at jdk.nashorn.internal.scripts.Script$\\^eval\\_.L:25$L:306(<eval>:323)\ \	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:537)\ \	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)\ \	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)\ \	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:185)\ \	at com.baasbox.service.scripting.js.Nashorn.emitEvent(Nashorn.java:192)\ \	at com.baasbox.service.scripting.js.Nashorn.eval(Nashorn.java:92)\ \	at com.baasbox.service.scripting.js.NashornEngine.eval(NashornEngine.java:72)\ \	at com.baasbox.service.scripting.ScriptingService.invoke(ScriptingService.java:285)\ \	at com.baasbox.controllers.ScriptInvoker.invoke(ScriptInvoker.java:77)\ \	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$129$$anonfun$apply$129.apply(routes_routing.scala:1735)\ \	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$129$$anonfun$apply$129.apply(routes_routing.scala:1735)\ \	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183)\ \	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377)\ \	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56)\ \	at play.GlobalSettings$1.call(GlobalSettings.java:64)\ \	at com.baasbox.controllers.actions.filters.ExtractQueryParameters.call(ExtractQueryParameters.java:44)\ \	at com.baasbox.controllers.actions.filters.ConnectToDBFilter.call(ConnectToDBFilter.java:81)\ \	at com.baasbox.controllers.actions.filters.UserOrAnonymousCredentialsFilter.call(UserOrAnonymousCredentialsFilter.java:107)\ \	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91)\ \	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90)\ \	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)\ \	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)\ \	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)\ \	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)\ \	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)\ \	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)\ \	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)\ \	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)\ \	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\ \	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\ \	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\ \	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\ Caused by: java.lang.NullPointerException\ \	at com.baasbox.commands.DBResource.exec(DBResource.java:124)\ \	at com.baasbox.commands.DBResource$$Lambda$39/176480830.execute(Unknown Source)\ \	at com.baasbox.commands.Resource.execute(Resource.java:57)\ \	at com.baasbox.commands.CommandRegistry.execute(CommandRegistry.java:70)\ \	at com.baasbox.service.scripting.js.Api.execCommand(Api.java:56)\ \	at jdk.nashorn.internal.scripts.Script$\\^eval\\_.L:25$Module$L:155(<eval>:167)\ \	... 46 more\ \ \	at com.baasbox.service.scripting.js.Nashorn.eval(Nashorn.java:110)\ \	at com.baasbox.service.scripting.js.NashornEngine.eval(NashornEngine.java:72)\ \	at com.baasbox.service.scripting.ScriptingService.invoke(ScriptingService.java:285)\ \	at com.baasbox.controllers.ScriptInvoker.invoke(ScriptInvoker.java:77)\ \	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$129$$anonfun$apply$129.apply(routes_routing.scala:1735)\ \	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$129$$anonfun$apply$129.apply(routes_routing.scala:1735)\ \	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183)\ \	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377)\ \	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56)\ \	at play.GlobalSettings$1.call(GlobalSettings.java:64)\ \	at com.baasbox.controllers.actions.filters.ExtractQueryParameters.call(ExtractQueryParameters.java:44)\ \	at com.baasbox.controllers.actions.filters.ConnectToDBFilter.call(ConnectToDBFilter.java:81)\ \	at com.baasbox.controllers.actions.filters.UserOrAnonymousCredentialsFilter.call(UserOrAnonymousCredentialsFilter.java:107)\ \	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91)\ \	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90)\ \	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)\ \	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)\ \	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)\ \	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)\ \	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)\ \	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)\ \	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)\ \	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)\ \	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\ \	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\ \	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\ \	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\ Caused by: <eval>:176:16 java.lang.NullPointerException\ \	at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:111)\ \ at jdk.nashorn.internal.scripts.Script$\\^eval\\_.L:25$Module$L:155(<eval>:176)\ \	at jdk.nashorn.internal.scripts.Script$baasbox_core.:scopeCall(baasbox.core)\ \	at jdk.nashorn.internal.scripts.Script$baasbox_core.L:134(baasbox.core:141)\ \	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:539)\ \	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)\ \	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)\ \	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:109)\ \	at jdk.nashorn.internal.scripts.Script$locations_import.L:89(locations.import:107)\ \	at jdk.nashorn.internal.scripts.Script$locations_import.L:1(locations.import:10)\ \	at jdk.nashorn.internal.scripts.Script$\\^eval\\_.L:25$ModuleRef$L:282$L:284(<eval>:288)\ \	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:537)\ \	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)\ \	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)\ \	at jdk.nashorn.internal.objects.NativeFunction.apply(NativeFunction.java:130)\ \	at jdk.nashorn.internal.scripts.Script$\\^eval\\_.L:25$L:306(<eval>:323)\ \	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:537)\ \	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)\ \	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)\ \	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:185)\ \	at com.baasbox.service.scripting.js.Nashorn.emitEvent(Nashorn.java:192)\ \	at com.baasbox.service.scripting.js.Nashorn.eval(Nashorn.java:92)\ \	... 26 more\ Caused by: java.lang.NullPointerException\ \	at com.baasbox.commands.DBResource.exec(DBResource.java:124)\ \	at com.baasbox.commands.DBResource$$Lambda$39/176480830.execute(Unknown Source)\ \	at com.baasbox.commands.Resource.execute(Resource.java:57)\ \	at com.baasbox.commands.CommandRegistry.execute(CommandRegistry.java:70)\ \	at com.baasbox.service.scripting.js.Api.execCommand(Api.java:56)\ \	at jdk.nashorn.internal.scripts.Script$\\^eval\\_.L:25$Module$L:155(<eval>:167)\ \	... 46 more\ "

**Comment by giastfader** [comment]
It seems that second statement does not return anything.
As a temporary workaround try:
Box.DB.exec("alter property Country.EN collate ci; select 1");

**Comment by giastfader** [comment]
for future reference the problem is caused by https://github.com/baasbox/baasbox/blob/11a5d6441b111db1599d49a180caa9940096654a/app/com/baasbox/commands/DBResource.java#L124

**Comment by avently** [comment]
Nope, this also doesn't work.

Interesting part of log is:

Caused by: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.alter property Country.EN collate ci; select 1
	at com.orientechnologies.orient.core.storage.OStorageEmbedded.executeCommand(OStorageEmbedded.java:120)
	at com.orientechnologies.orient.core.storage.OStorageEmbedded.command(OStorageEmbedded.java:103)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:59)
	at com.baasbox.db.DbHelper.genericSQLCommandExecute(DbHelper.java:273)
	at com.baasbox.db.DbHelper.genericSQLStatementExecute(DbHelper.java:286)
	at com.baasbox.commands.DBResource.exec(DBResource.java:120)
	at com.baasbox.commands.DBResource$$Lambda$38/181485407.execute(Unknown Source)
	at com.baasbox.commands.Resource.execute(Resource.java:57)
	at com.baasbox.commands.CommandRegistry.execute(CommandRegistry.java:70)
	at com.baasbox.service.scripting.js.Api.execCommand(Api.java:56)
	at jdk.nashorn.internal.scripts.Script$\^eval\_.L:25$Module$L:155(<eval>:167)
	... 45 more
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.metadata.schema.OPropertyImpl.toStream(OPropertyImpl.java:991)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.toStream(OClassImpl.java:691)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.toStream(OSchemaShared.java:872)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.save(ODocumentWrapperNoClass.java:83)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.saveInternal(OSchemaShared.java:962)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.releaseSchemaWriteLock(OSchemaShared.java:751)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.releaseSchemaWriteLock(OClassImpl.java:1521)
	at com.orientechnologies.orient.core.metadata.schema.OPropertyImpl.releaseSchemaWriteLock(OPropertyImpl.java:1012)
	at com.orientechnologies.orient.core.metadata.schema.OPropertyImpl.setCollate(OPropertyImpl.java:879)
	at com.orientechnologies.orient.core.metadata.schema.OPropertyImpl.set(OPropertyImpl.java:824)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAlterProperty.execute(OCommandExecutorSQLAlterProperty.java:118)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:60)
	at com.orientechnologies.orient.core.storage.OStorageEmbedded.executeCommand(OStorageEmbedded.java:114)
	... 55 more
