### ISSUE TITLE
Routes in plugins

### ISSUE THREAD

**Issue by avently** [baasbox/baasbox#742]
I see you are using routes file in your Java app - https://github.com/baasbox/baasbox/blob/master/conf/routes. It's really cool thing. 

This file can help you map all your app. Can you imaging how wonderful will be if you can make something like routes for plugins?

For now, i have 5 plugins per one CRUD. For example, message.manage -> messages.create, message.get, messages.edit, messages.delete. First file just imports others. Import takes about 0.2 second per one file. That's mean i lost 0.2 second. If i will have an routes file, i can map all links to plugins like you did and save query time.

**Comment by giastfader** [comment]
Why did you write 4 plugins to implement CRUD operations?
You can write just one plugin that answers to the 4 HTTP verb: GET,POST,PUT, DELETE.

```
http()
 .get(function(req){
   .....
 })
 .post(function(req){
  ......
 })
.put(function(req){
  ......
 })
.delete(function(req){
  ......
 })
```

**Comment by avently** [comment]
I know. I did it because one plugin with all this methods looks to huge (3-7 screens). I can't maintain this code:) 
So I created one file that imports other files and responds to CRUD.
