### ISSUE TITLE
Error building BaaBox (play clean-all baas)

### ISSUE THREAD

**Issue by guiduroy** [baasbox/baasbox#747]
i am unable to build the BaasBox source code with 100 errors : 
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/BaseRestResource.java:41: error: ')' expected
[error]     protected static final Predicate<BaasBoxPrivateFields> removeVisible = ((Predicate<BaasBoxPrivateFields>)BaasBoxPrivateFields::isVisibleByTheClient).negate();
[error]                                                                                                                                  ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/BaseRestResource.java:41: error: illegal start of type
[error]     protected static final Predicate<BaasBoxPrivateFields> removeVisible = ((Predicate<BaasBoxPrivateFields>)BaasBoxPrivateFields::isVisibleByTheClient).negate();
[error]                                                                                                                                   ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/BaseRestResource.java:41: error: ';' expected
[error]     protected static final Predicate<BaasBoxPrivateFields> removeVisible = ((Predicate<BaasBoxPrivateFields>)BaasBoxPrivateFields::isVisibleByTheClient).negate();
[error]                                                                                                                                                        ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/BaseRestResource.java:41: error: invalid method declaration; return type required
[error]     protected static final Predicate<BaasBoxPrivateFields> removeVisible = ((Predicate<BaasBoxPrivateFields>)BaasBoxPrivateFields::isVisibleByTheClient).negate();
[error]                                                                                                                                                          ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/BaseRestResource.java:45: error: ')' expected
[error] 	                                                                        .map(BaasBoxPrivateFields::toString)
[error] 	                                                                                                 ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/BaseRestResource.java:45: error: illegal start of type
[error] 	                                                                        .map(BaasBoxPrivateFields::toString)
[error] 	                                                                                                  ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/BaseRestResource.java:45: error: ';' expected
[error] 	                                                                        .map(BaasBoxPrivateFields::toString)
[error] 	                                                                                                           ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/BaseRestResource.java:46: error: invalid method declaration; return type required
[error] 	                                                                        .collect(Collectors.toSet());
[error] 	                                                                         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/BaseRestResource.java:46: error: <identifier> expected
[error] 	                                                                        .collect(Collectors.toSet());
[error] 	                                                                                                 ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/BaseRestResource.java:46: error: ';' expected
[error] 	                                                                        .collect(Collectors.toSet());
[error] 	                                                                                                  ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/BaseRestResource.java:46: error: illegal start of type
[error] 	                                                                        .collect(Collectors.toSet());
[error] 	                                                                                                   ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/BaseRestResource.java:46: error: <identifier> expected
[error] 	                                                                        .collect(Collectors.toSet());
[error] 	                                                                                                    ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/BaseRestResource.java:46: error: ';' expected
[error] 	                                                                        .collect(Collectors.toSet());
[error] 	                                                                                                     ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:48: error: ')' expected
[error]                         .put("switchUser", DBResource::switchUser)
[error]                                                      ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:48: error: illegal start of type
[error]                         .put("switchUser", DBResource::switchUser)
[error]                                                       ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:48: error: ';' expected
[error]                         .put("switchUser", DBResource::switchUser)
[error]                                                                  ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:49: error: invalid method declaration; return type required
[error]                         .put("isAdmin",DBResource::isConnectedAsAdmin)
[error]                          ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:49: error: illegal start of type
[error]                         .put("isAdmin",DBResource::isConnectedAsAdmin)
[error]                              ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:49: error: <identifier> expected
[error]                         .put("isAdmin",DBResource::isConnectedAsAdmin)
[error]                                                  ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:49: error: ';' expected
[error]                         .put("isAdmin",DBResource::isConnectedAsAdmin)
[error]                                                   ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:49: error: <identifier> expected
[error]                         .put("isAdmin",DBResource::isConnectedAsAdmin)
[error]                                                                      ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:50: error: illegal start of type
[error]                         .put("beginTransaction",DBResource::beginTransaction)
[error]                         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:50: error: illegal start of type
[error]                         .put("beginTransaction",DBResource::beginTransaction)
[error]                              ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:50: error: <identifier> expected
[error]                         .put("beginTransaction",DBResource::beginTransaction)
[error]                                                           ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:50: error: ';' expected
[error]                         .put("beginTransaction",DBResource::beginTransaction)
[error]                                                            ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:50: error: <identifier> expected
[error]                         .put("beginTransaction",DBResource::beginTransaction)
[error]                                                                             ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:51: error: illegal start of type
[error]                         .put("isInTransaction",DBResource::isInTransaction)
[error]                         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:51: error: illegal start of type
[error]                         .put("isInTransaction",DBResource::isInTransaction)
[error]                              ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:51: error: <identifier> expected
[error]                         .put("isInTransaction",DBResource::isInTransaction)
[error]                                                          ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:51: error: ';' expected
[error]                         .put("isInTransaction",DBResource::isInTransaction)
[error]                                                           ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:51: error: <identifier> expected
[error]                         .put("isInTransaction",DBResource::isInTransaction)
[error]                                                                           ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:52: error: illegal start of type
[error]                         .put("commitTransaction",DBResource::commitTransaction)
[error]                         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:52: error: illegal start of type
[error]                         .put("commitTransaction",DBResource::commitTransaction)
[error]                              ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:52: error: <identifier> expected
[error]                         .put("commitTransaction",DBResource::commitTransaction)
[error]                                                            ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:52: error: ';' expected
[error]                         .put("commitTransaction",DBResource::commitTransaction)
[error]                                                             ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:52: error: <identifier> expected
[error]                         .put("commitTransaction",DBResource::commitTransaction)
[error]                                                                               ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:53: error: illegal start of type
[error]                         .put("rollbackTransaction",DBResource::rollbackTransaction)
[error]                         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:53: error: illegal start of type
[error]                         .put("rollbackTransaction",DBResource::rollbackTransaction)
[error]                              ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:53: error: <identifier> expected
[error]                         .put("rollbackTransaction",DBResource::rollbackTransaction)
[error]                                                              ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:53: error: ';' expected
[error]                         .put("rollbackTransaction",DBResource::rollbackTransaction)
[error]                                                               ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:53: error: <identifier> expected
[error]                         .put("rollbackTransaction",DBResource::rollbackTransaction)
[error]                                                                                   ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:54: error: illegal start of type
[error]                         .put("isAnId",DBResource::isAnId)
[error]                         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:54: error: illegal start of type
[error]                         .put("isAnId",DBResource::isAnId)
[error]                              ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:54: error: <identifier> expected
[error]                         .put("isAnId",DBResource::isAnId)
[error]                                                 ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:54: error: ';' expected
[error]                         .put("isAnId",DBResource::isAnId)
[error]                                                  ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:54: error: <identifier> expected
[error]                         .put("isAnId",DBResource::isAnId)
[error]                                                         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:55: error: illegal start of type
[error]                         .put("select",DBResource::select)
[error]                         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:55: error: illegal start of type
[error]                         .put("select",DBResource::select)
[error]                              ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:55: error: <identifier> expected
[error]                         .put("select",DBResource::select)
[error]                                                 ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:55: error: ';' expected
[error]                         .put("select",DBResource::select)
[error]                                                  ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:55: error: <identifier> expected
[error]                         .put("select",DBResource::select)
[error]                                                         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:56: error: illegal start of type
[error]                         .put("exec",DBResource::exec)
[error]                         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:56: error: illegal start of type
[error]                         .put("exec",DBResource::exec)
[error]                              ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:56: error: <identifier> expected
[error]                         .put("exec",DBResource::exec)
[error]                                               ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:56: error: ';' expected
[error]                         .put("exec",DBResource::exec)
[error]                                                ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:56: error: <identifier> expected
[error]                         .put("exec",DBResource::exec)
[error]                                                     ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:57: error: illegal start of type
[error]                         .build();
[error]                         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:86: error: illegal start of expression
[error]         if (qryParams!=null) qryParams.forEach(j->{
[error]                                                  ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:86: error: illegal start of expression
[error]         if (qryParams!=null) qryParams.forEach(j->{
[error]                                                   ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:86: error: ';' expected
[error]         if (qryParams!=null) qryParams.forEach(j->{
[error]                                                    ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:87: error: not a statement
[error]             if (j==null) params.add(null);
[error]                ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:87: error: ';' expected
[error]             if (j==null) params.add(null);
[error]                         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:88: error: 'else' without 'if'
[error]             else params.add(j.asText());
[error]             ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:89: error: illegal start of type
[error]         });
[error]          ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:91: error: illegal start of type
[error] 		try {
[error] 		^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:91: error: ';' expected
[error] 		try {
[error] 		   ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:94: error: <identifier> expected
[error] 	        BaasBoxLogger.debug("Query result: ");
[error] 	                           ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:94: error: illegal start of type
[error] 	        BaasBoxLogger.debug("Query result: ");
[error] 	                            ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:95: error: <identifier> expected
[error] 	        BaasBoxLogger.debug(s);
[error] 	                           ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:95: error: <identifier> expected
[error] 	        BaasBoxLogger.debug(s);
[error] 	                             ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:96: error: <identifier> expected
[error] 			lst = (ArrayNode)Json.mapper().readTree(s);
[error] 			   ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:97: error: class, interface, or enum expected
[error] 		} catch (IOException e) {
[error] 		  ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:99: error: class, interface, or enum expected
[error] 		} catch(OQueryParsingException e){
[error] 		^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:101: error: class, interface, or enum expected
[error] 		}
[error] 		^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:103: error: class, interface, or enum expected
[error]     }
[error]     ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:108: error: class, interface, or enum expected
[error]     	String statement = jParams.get("statement").asText();
[error]     	^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:109: error: class, interface, or enum expected
[error]     	BaasBoxLogger.debug("Executing statement from a plugin: " + statement);
[error]     	^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:111: error: class, interface, or enum expected
[error]         ArrayNode qryParams = (ArrayNode) jParams.get("array_of_params");
[error]         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:113: error: class, interface, or enum expected
[error]         ArrayList params=new ArrayList();
[error]         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:114: error: class, interface, or enum expected
[error]         if (qryParams!=null) qryParams.forEach(j->{
[error]         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:116: error: class, interface, or enum expected
[error]             else params.add(j.asText());
[error]             ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:117: error: class, interface, or enum expected
[error]         });
[error]         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:118: error: class, interface, or enum expected
[error]         JsonNode lst;
[error]         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:119: error: class, interface, or enum expected
[error] 		try {
[error] 		^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:121: error: class, interface, or enum expected
[error] 	        String s = "";
[error] 	        ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:122: error: class, interface, or enum expected
[error] 	        if (listToReturn instanceof List ) s=JSONFormats.prepareResponseToJson((List)listToReturn, JSONFormats.Formats.GENERIC,true);
[error] 	        ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:123: error: class, interface, or enum expected
[error] 	        else if (listToReturn instanceof ODocument) s=JSONFormats.prepareResponseToJson((ODocument)listToReturn, JSONFormats.Formats.GENERIC,true);
[error] 	        ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:124: error: class, interface, or enum expected
[error] 	        else s=listToReturn.toString();
[error] 	        ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:125: error: class, interface, or enum expected
[error] 	        BaasBoxLogger.debug("Statement result: ");
[error] 	        ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:126: error: class, interface, or enum expected
[error] 	        BaasBoxLogger.debug(s);
[error] 	        ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:127: error: class, interface, or enum expected
[error] 			lst = Json.mapper().readTree(s);
[error] 			^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:128: error: class, interface, or enum expected
[error] 		} catch (IOException e) {
[error] 		^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:130: error: class, interface, or enum expected
[error] 		} catch(OQueryParsingException e){
[error] 		^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:132: error: class, interface, or enum expected
[error] 		}
[error] 		^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:134: error: class, interface, or enum expected
[error]     }
[error]     ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:139: error: class, interface, or enum expected
[error]         return NullNode.getInstance();
[error]         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:140: error: class, interface, or enum expected
[error]     }
[error]     ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:144: error: class, interface, or enum expected
[error]         return NullNode.getInstance();
[error]         ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:145: error: class, interface, or enum expected
[error]     }
[error]     ^
[error] /Users/Guillaume/Downloads/baasbox-master/app/com/baasbox/commands/DBResource.java:149: error: class, interface, or enum expected
[error]         return NullNode.getInstance();
[error]         ^
[error] 100 errors
[error] (compile:compile) javac returned nonzero exit code

**Comment by giastfader** [comment]
The first error says me that you are not compiling BaasBox server with javac 1.8

**Comment by guiduroy** [comment]
my bad, i didn't see in the prerequisites it required version 8. Thank you for the response.

by the way its "the first error tells me" :)

**Comment by giastfader** [comment]
Thanks :)
