### ISSUE TITLE
Anonymous access to links

### ISSUE THREAD

**Issue by zebehringer** [baasbox/baasbox#752]
Without a session (i.e. as an anonymous user) I can query all documents that have been granted to the 'anonymous' role, but I get an error if I try to do the same for links. This command `curl -X GET -H x-baasbox-appcode:0123456789 "http://localhost:9000/link"` returns this response: ```{"result":"error","message":"Missing both Session Token and Authorization info","resource":"/link","method":"GET","request_header":{"Accept":["*/*"],"Host":["localhost:9000"],"User-Agent":["curl/7.30.0"],"x-baasbox-appcode":["0123456789"]},"API_version":"0.9.2","http_code":401}```

That may be working as designed since I don't see a way to control link access other than by doing so to the nodes that are being linked.

However, with the plugin API, I can query links as an anonymous user, which returns results (not an error), but the __in__ or __out__ attribute of the link result will be null if that node isn't readable by anonymous users. I think the fact that an error is not returned is inconsistent with the above scenario. Even if an error was not returned, I would expect that the results with the null __in__ or __out__ attribute would be automatically filtered out.

**Comment by giastfader** [comment]
This is by design.
Link REST APIs are not accessible by anonymous users, but the related data are.
This means, as you noted, that  Links info can be retrieved inside a plugin.
Of course if the linked nodes have restricted access you cannot see them.
If you want to filter out the null nodes you can specify a "where" condition.
