### ISSUE TITLE
download failed: com.github.stephenc.eaio-grabbag#grabbag;1.8.1!grabbag.non-maven-jar

### ISSUE THREAD

**Issue by griffinl** [baasbox/baasbox#771]
I get this message after I change the eaio dependency to "com.github.stephenc.eaio-uuid" % "uuid" % "3.4.0" as I can not connect to eaio.com/maven2. 
Anyone can help me to solve this issue ?

**Comment by eliantor** [comment]
Why did you change the dependency in the first place?

**Comment by eliantor** [comment]
Btw the version you are trying to check out is on maven central:
http://search.maven.org/#artifactdetails%7Ccom.github.stephenc.eaio-uuid%7Cuuid%7C3.4.0%7Cjar

most likely, this is a problem with your network.

Please don't pollute the issues

**Comment by griffinl** [comment]
You are right, it's network problem as I am in china. I will try to find another way to get the libs.
