### ISSUE TITLE
BaasBox 0.9.2 Admin Console Upload Push Certificate Error

### ISSUE THREAD

**Issue by jaylagare** [baasbox/baasbox#778]
I have BaasBox installed on a remote server behind an HTTPS reverse proxy. I'm encountering the following error when I try to upload push certificates from the admin console:
OPTIONS https://localhost:9000/admin/configuration/Push/dummy/profile1.production.ios.certificate/push_production.p12 net::ERR_CONNECTION_CLOSED

**Comment by giastfader** [comment]
maybe it is the same of #720
