### ISSUE TITLE
How to create Admin User (not admin console) in Baas Box? [Question]

### ISSUE THREAD

**Issue by LOG-TAG** [baasbox/baasbox#782]
I'm a begginer in Baasbox! Our requirement needs admin user !! For example If I create to do list mobile app for enterprise, that app will have ADMIN user such that  should return all data of all users with any filters that can be used for graph or user management !! 

currently in baasbox  ADMIN console is available !! Is there any REST API available for accessing the ADMIN console data ?

by using the plugin I can create ADMIN user ?
Ex:
Admin
Some APIs to create collections or drop them require you to be an administrator. But you may want to expose endpoints which do something that is normally not available to other roles. For such cases a special API is exposed:

var result = Box.runAsAdmin(function(){
 // inside this block of code you are an administrator
 var isTrue =Box.isAdmin();
 return 2;
});

using this plugin we can get the data for all users for admin user/atleast admin console?

Thanks

**Comment by LOG-TAG** [comment]
I think this will be the solution: http://baasbox-docs.readthedocs.org/en/0.7.2/RestAPI/Admin/admin_users.html

**Comment by giastfader** [comment]
Yes, you can use the runAsAdmin() helper to wrap any code that needs high privileges. And of course you can returns any data to the client.
However, administrators have dedicated APIs that are not documented yet.
These APIs are called by the Console.
I think that you need this one https://github.com/baasbox/baasbox/blob/0.9.2/conf/routes#L268
