### ISSUE TITLE
Image resizing on the fly

### ISSUE THREAD

**Issue by avently** [baasbox/baasbox#793]
The idea to resize an image after upload is not good. Because every resized image costs money (it stored on a hard drive) and sizes for images may be changed in the future. That's why 500px uses image resizing on the fly when user wants to see thumbnail. It's a good idea. 

Would be cool to see it in BaasBox.

**Comment by giastfader** [comment]
The images are resized (and then cached on the db) after the first call.
This has been chosen because image resizing can be a very high CPU expensive task, all the more so if you consider that the server can receive many resize requests at the same time.
May be with can introduce a new key into the setting panel to disable this feature.

WDYT?

**Comment by avently** [comment]
I don't know about how much CPU this operation needs. So if you said that ok, your idea with the key in settings is good I think. 

Do you know a way to minimize CPU usage for this kind of task? I know that 500px uses this tool: http://www.vips.ecs.soton.ac.uk/index.php?title=VIPS

~ 150 ms per image.

Another question. What do you think about storing files in DB? Is it a good idea (easy to use & file size & retrieving speed)? Maybe we should save it in a folder like files in finder? I said that because when OrientDB will copy itself (for better performance) all files will be copied too. This means that really huge data will be saved to many hard disks.

**Comment by avently** [comment]
About the last idea. 
As you know, SSD disks have a limited number of read/write operations. This means that we should scale our OrientDB horizontally. This means we should copy DB on many hard disks. When files will be in DB we will spend more money (disks x n). 

I can suggest another choice. When user wants to upload a file Baasbox should save info in the DB (as it do it now) and then send the file to another instance, for example, mysiteurl.com:1000/upload with ID of the file (from DB) and with the file itself. That's it. 

Another instance should save the file in a folder with chosen name (ID from the DB). 

When user wants to get a picture he just ask mysiteurl.com:1000/file/ID or file/ID_size1 or file/ID_100x200. 

The instance I'm talking about is a server with simple app that should have one page of code: get & write a file and post the file back. It should listen a port that could be saved in settings.txt. 

The idea is simple as 2+2. Of course we as developers can setup some cache apps on the instance with port 1000. 

I thought about it a couple of hours and it looks good. 

@giastfader, WDYT?

**Comment by avently** [comment]
Example of upload/download. 
http://docs.oracle.com/javaee/6/tutorial/doc/glraq.html
