### ISSUE TITLE
Failure to start server on OpenShift during GIT PUSH

### ISSUE THREAD

**Issue by jfrfonseca** [baasbox/baasbox#805]
I followed to the letter the tutorial at http://www.baasbox.com/deploy-baasbox-on-openshift/ , to the point of creating an app with the precise same name described in the tutorial (it is the second try to make it work). However, when I try to access it in my browser (Firefox on Ubuntu Linux) receive an error 503 where the BaaSbox admin page should be.

I believe that some error occurred during the execution of the START script, after the GIT PUSH command at the end of the tutorial.

Those are the personal-information-redacted LOGS of the GIT command on my machine:

<<REDACTED>>@<<REDACTED>>:~/openshift/baasbox$ git push
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

In Git 2.0, Git will default to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Counting objects: 170, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (164/164), done.
Writing objects: 100% (165/165), 82.20 MiB | 380.00 KiB/s, done.
Total 165 (delta 2), reused 0 (delta 0)
remote: Stopping DIY cartridge
remote: Building git ref 'master', commit 042deaa
remote: Preparing build for deployment
remote: Deployment id is 5aa16547
remote: Activating deployment
remote: Starting DIY cartridge
remote: rm: cannot remove `/var/lib/openshift/<<REDACTED>>/app-root/runtime/repo//bin/RUNNING_PID': No such file or directory
remote: Play server process ID is 299472
remote: Oops, cannot start the server.
remote: @6mpb9oi8b: Cannot init the Global object
remote: 	at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:55)
remote: 	at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:49)
remote: 	at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
remote: 	at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$globalInstance(Application.scala:48)
remote: 	at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalInstance$lzycompute(Application.scala:399)
remote: 	at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalInstance(Application.scala:399)
remote: 	at play.api.WithDefaultGlobal$class.global(Application.scala:64)
remote: 	at play.api.DefaultApplication.global(Application.scala:399)
remote: 	at play.api.WithDefaultConfiguration$class.play$api$WithDefaultConfiguration$$fullConfiguration(Application.scala:78)
remote: 	at play.api.DefaultApplication.play$api$WithDefaultConfiguration$$fullConfiguration$lzycompute(Application.scala:399)
remote: 	at play.api.DefaultApplication.play$api$WithDefaultConfiguration$$fullConfiguration(Application.scala:399)
remote: 	at play.api.WithDefaultConfiguration$class.configuration(Application.scala:80)
remote: 	at play.api.DefaultApplication.configuration(Application.scala:399)
remote: 	at play.api.Application$class.$init$(Application.scala:272)
remote: 	at play.api.DefaultApplication.<init>(Application.scala:399)
remote: 	at play.core.StaticApplication.<init>(ApplicationProvider.scala:50)
remote: 	at play.core.server.NettyServer$.createServer(NettyServer.scala:280)
remote: 	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:316)
remote: 	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:311)
remote: 	at scala.Option.map(Option.scala:145)
remote: 	at play.core.server.NettyServer$.main(NettyServer.scala:311)
remote: 	at play.core.server.NettyServer.main(NettyServer.scala)
remote: Caused by: java.lang.UnsupportedClassVersionError: com/baasbox/Global : Unsupported major.minor version 52.0
remote: 	at java.lang.ClassLoader.defineClass1(Native Method)
remote: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
remote: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
remote: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
remote: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
remote: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
remote: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
remote: 	at java.security.AccessController.doPrivileged(Native Method)
remote: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
remote: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
remote: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
remote: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
remote: 	at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$javaGlobal(Application.scala:28)
remote: 	at play.api.DefaultApplication.play$api$WithDefaultGlobal$$javaGlobal$lzycompute(Application.scala:399)
remote: 	at play.api.DefaultApplication.play$api$WithDefaultGlobal$$javaGlobal(Application.scala:399)
remote: 	at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:50)
remote: 	... 21 more
remote: -------------------------
remote: Git Post-Receive Result: success
remote: Activation status: success
remote: Deployment completed with status: success
To <<REDACTED>>@baasbox-jfrafditt0.rhcloud.com/~/git/baasbox.git/
   fbaa73e..042deaa  master -> master

**Comment by giastfader** [comment]
The cause is "Caused by: java.lang.UnsupportedClassVersionError: com/baasbox/Global : Unsupported major.minor version 52.0" 
BaasBox needs Java 8.

AFAIK OpenShift has Java 7 by default
