### ISSUE TITLE
Grant permissions for collections

### ISSUE THREAD

**Issue by meeximum** [baasbox/baasbox#855]
Is it possible to grant a permission for all documents of a certain collection? So new documents automatically are visible for the authorized users?

**Comment by giastfader** [comment]
Actually it is not possible because permissions are based on OrientDB "record level security" feature (http://orientdb.com/docs/1.7.8/orientdb.wiki/Security.html#record-level-security ) that works on record level.
At best we can think to implement collections that don't use permissions at all.

**Comment by meeximum** [comment]
ok.
I've created a plugin, which creates a doc and then grants read privs to a certain role, works perfectly :-)

**Comment by bennythomps** [comment]
@meeximum would you be willing to share the code for the plugin? Seems useful!

**Comment by meeximum** [comment]
Sure
    http().post(function(req){        
        var doc = Box.Documents.save("myCollection", req.body);
    
        Box.Documents.grant("projects",doc.id,
        {
            roles: {
                read:["xxx"]
            },
            users: {
                read:["xxx"]
            }
        });    
        return {status: 200, content: doc};
    });

Post body is the same as when creating a document
