### ISSUE TITLE
[1.0.0-M3][20151004-nightly] Error on uploading files

### ISSUE THREAD

**Issue by alextosatto** [baasbox/baasbox#887]
When I try to upload a file with ACL from iOS SDK I'll get NullPointerException. Note that the same function was working on BB 0.9.4.

When the ACL is either of type
  [
      read: { roles = ( anonymous ); users = ( "xxxx" ); },
      delete: { },
      update: { users = ( "xxxx" ); }
  ]
or
  [
      read: { users = ( "xxxx", "yyyy" ); },
      delete: { },
      update: { users = ( "xxxx" ); }
  ]
the exception I'll get is:
Caused by: java.lang.NullPointerException\n\tat
- com.baasbox.dao.UserDao.existsUserName(UserDao.java:113)\n\tat
- com.baasbox.service.user.UserService.exists(UserService.java:558)\n\tat
- com.baasbox.controllers.File.storeFile(File.java:187)\n\tat 

Otherwise if the ACL is of type
  [
      read: { roles = ( anonymous ); },
      delete: { },
      update: { users = ( "xxxx" ); }
  ]
I'll see:
Caused by: java.lang.NullPointerException\n\tat 
- com.baasbox.dao.RoleDao.exists(RoleDao.java:107)\n\tat
- com.baasbox.service.user.RoleService.exists(RoleService.java:50)\n\tat
- com.baasbox.controllers.File.storeFile(File.java:191)\n\tat 

To have the full stacktrace email me.

**Comment by giastfader** [comment]
The db connection is not available during the preliminary check on users/roles indicated into the ACL.
