### ISSUE TITLE
Will Box WS drop the headers when working in plugin mode?

### ISSUE THREAD

**Issue by weahoo** [baasbox/baasbox#891]
Hi,
I trying to use the walk-around approach to enable the file grants in the plugin engine, it works in this way: once the plugin retrieves the request, it will use the REST API to login as the admin, and grant/revoke file permission to the specific user. In this manner, permission grants worked properly, but the revoking of file NOT. The following is the code section:
```javascript
http().get(function(req){
    // login as the admin in backoffice and retrieve the session token.
    var params = req.queryString;
    var me = Box.Users.me();
    var result = Box.WS.post("http://localhost:9000/login",
    "&password=admin&appcode=1234567890&username=admin&",
        {params: {
        },
        headers: {"Content-Type":"application/x-www-form-urlencoded"}
    });
    // parse the session token since the charactors cannot be extracted properly at present.
    var token = result.body.data;
    
    var obj = JSON.stringify(token);
    
    var index = obj.indexOf("X-BB-SESSION");
    var session_token = (obj.substr(index+15, 36));
    // request the file grant action via REST API. This action is made via administrator permission, please take care.
    if(params.id==null){
        return {status:400, content: "file id is not yet defined"};
    }
    if(params.action == null){
        return {status:400, content: "assigned permission is required, read/update/delete/all, one of them is required"};
    }
    if(params.action == "read"){
        Box.log(params.action);
        result = Box.WS.delete("http://localhost:9000/file/" + params.id + "/read/user/" + me.user.name, "&&", 
        {params:{}, 
        headers:{"Content-Type":"application/x-www-form-urlencoded", 
            "X-BB-SESSION": session_token,
            "X-BAASBOX-APPCODE":"1234567890"
            
        }
        
        });
        return {status: 200, content: result};
        
    }
    else{
         return {status:400, content: "assigned permission is required, read/update/delete/all, one of them is required"};
  
    }
});
```
The error message is returned as the following:
{"status":400,"body":{"result":"error","message":"Missing Session Token, Authorization info and even the AppCode","resource":"/file/1504c273-4a5d-4e04-b3ad-7cc07594b6bf/read/user/demo","method":"DELETE","request_header":{"Accept":["*/*"],"Connection":["keep-alive"],"Host":["localhost:9000"],"User-Agent":["NING/1.0"]},"API_version":"0.9.4"}}

The revoking worked properly in common client mode.

The message indicates either the session token or appcode was not carried properly and therefore such an issue occurs, but if we replaced the DELETE action with GET, it worked properly. Is there anybody has idea on this?

Best regards
Y.

**Comment by giastfader** [comment]
Why don't you do just:

```
var token = result.body.data["X-BB-SESSION"];
````

?

BTW, you can call a BaasBox API also using BASIC AUTH, so you do not need to execute a login anytime.

**Comment by weahoo** [comment]
Thanks, I just noticed this option. Do you have any idea on my question? I mean the grant permission without any issues, but http DELETE met such an issue...

**Comment by giastfader** [comment]
If the session token is correct, try to remove the content-type header.

**Comment by weahoo** [comment]
Tried but same response, as console debug output, the following messages were given:

2015-11-13 14:48:53.246+0000 [com.motionext.ungrant_file]: {"status":200,"body":{"result":"ok","data":{"user":{"roles":[{"name":"administrator","isrole":true},{"name":"friends_of_andrea","isrole":true}],"name":"admin","status":"ACTIVE"},"signUpDate":"2015-11-11T05:13:04.681+0000","X-BB-SESSION":"5a4372c2-604f-424e-b6ab-d767ce3c77f4"},"http_code":200}}
--------------------- The above is the admin login for the session token.
2015-11-13 14:48:53.257+0000 [com.motionext.ungrant_file]: 5a4372c2-604f-424e-b6ab-d767ce3c77f4
-------------- this is the output from the above script.
2015-11-13 14:48:53.260+0000 [com.motionext.ungrant_file]: http://localhost:9000/file/1504c273-4a5d-4e04-b3ad-7cc07594b6bf/read/user/demo
-------------- This intends to revoke the read permission for user demo.

**Comment by giastfader** [comment]
This is quite strane because the code is the same

**Comment by weahoo** [comment]
Yes, I checked the source code in core and play framework, it seems they are using same logic to handle the different HTTP method. I wonder if there was limits to do revoke, then I should not be able to do grant action as well, but I can do that. 
You can repeat these two cases, the only difference is 'Box.WS.delete' and 'Box.WS.get'...

**Comment by weahoo** [comment]
I thought this action is quite important, image the following scenario: After the mobile user purchased one file and of course the file permission should be granted to him. But once he revoke his purchase/subscription, the corresponding permission needs to be revoked. The plugin can be triggered by another service and therefore an admin session is required(it could be created by REST API or your mentioned Box User API, and then trigger the revoke action. 
If there is any walk-around approach, it would be appreciated as well.

**Comment by weahoo** [comment]
After trying to find other alternative, the following strange result was got:
I would like to find out the specific file owner, then try to create a session for the owner and try the revoke action via file owner. So the first step is finding the file details, the code attached:

```javascript
http().get(function(req){
    var params = req.queryString;
    
    var result = Box.WS.post("http://localhost:9000/login",
    "&password=admin&appcode=1234567890&username=admin&",
        {params: {
        },
        headers: {"Content-Type":"application/x-www-form-urlencoded"}
    });
    // parse the session token since the charactors cannot be extracted properly at present.
    var token = result.body.data["X-BB-SESSION"];
    Box.log(token);
    Box.log("http://localhost:9000/file/details/" + params.id);
    var final_result = Box.WS.get("http://localhost:9000/file/details/"  , "&&", 
        {params:{}, 
        headers:{ "Content-Type":"application/x-www-form-urlencoded", 
            "X-BB-SESSION": token,
            "X-BAASBOX-APPCODE":"1234567890"

        }
    });
    return {status: 200, content: final_result};    
});
```
The result is unexpected:
{
    "result": "ok",
    "data": {
        "status": 404,
        "body": "Resource /public/file/details/, method GET was not found on this server."
    },
    "http_code": 200
}
Any help is appreciated on this. And the Box session creation API is not yet available in the stable release, so I have to use REST again. V1.0 is expected.

**Comment by swampie** [comment]
in the code above it looks like you are missing the last segment of the path:

```
 Box.WS.get("http://localhost:9000/file/details/"
```

should be 

```
 Box.WS.get("http://localhost:9000/file/details/"+params.id[0]
```

and i think you should remove the "&&" argument and pass as second argument the  {params:...,headers:...} object

**Comment by weahoo** [comment]
You are right, and other issues were cleared after I remove "&&" argument and pass the json object for params and headers as the second argument. The following words may cause misuse like me:
"//IMPORTANT: put ALWAYS '&' chars before and after the body when use the application/x-www-form-urlencoded content-type" in the PluginApi document.
