### ISSUE TITLE
Enormous default.pcl file size

### ISSUE THREAD

**Issue by Sprechen** [baasbox/baasbox#914]
We are using the Baasbox version 0.9.4 in a production environment and we have noticed something strange.
We have found that the default.pcl database file is 6,7 Gb and it is growing very fast.
The database contains 16768 records, with a total amount of less then 10Mb (calculated using the documents "table" in the dashboard of the console page).
We also use the files storage to save photos uploaded by users. Now, we have 658 photos. Assuming a maximum size of 1MB for each photo (it is limited by our client), photos are stored (theoretically) in less then 1Gb.

Why the default.pcl is so big? What is stored inside it?
Is Baasbox saving some other data that cause the default.pcl size?

**Comment by giastfader** [comment]
Hi,
BaasBox uses OrientDB.
.pcl files are data files where the DBMS stores data.
Every collection should have its own .pcl file.
Into the default one BaasBox stores files blob and audit records. 
Data files always grow and space is not recycled when records are deleted.
Only way I know is to perform a full backup/restore.
You can try on a test machine.

Here are more details about OrientDB internals: http://orientdb.com/docs/1.7.8/orientdb.wiki/Paginated-Local-Storage.html

**Comment by Sprechen** [comment]
Thank you very much for your answer.

Thus, every uploaded photo goes in the default.pcl file. Is this correct?
But which type of audit records does Baasbox save? Can they be limited in some way? 
Does Baasbox log every query to this collection?

**Comment by Sprechen** [comment]
Looking in the source code, I found the Audit.java class (https://github.com/baasbox/baasbox/blob/master/app/com/baasbox/db/hook/Audit.java).

If I correctly understand the class, for each creation or editing of any document, Baasbox logs several info regarding it, correct?
However, I don't find any way to access these logs using the administration console, and thus I can't understand their usefulness.
In addition, since orientdb always increase its file size, in long term the solution to save all this logs in the database is not sustainable. A simpler log file could be, instead, very useful, since it would be possible to delete it when unnecessary, saving disk space.

Is there any way to fully disable this space-consuming feature?
I hope that there is a smarter way to do so than to modify the source code and recompiling it....

Thanks,
Luca

**Comment by giastfader** [comment]
After a deep investigation the result is that when a file is delete, its content (the BLOB) is not removed from the database and the space is not reused for future insertions.
This is a BUG that we have to fix ASAP.
