### ISSUE TITLE
Is it possible to interact with unauthenticated request via Plugin?

### ISSUE THREAD

**Issue by weahoo** [baasbox/baasbox#934]
Hi,
I noticed that the plugin can interact with authenticated request, is it possible to enable the plugin to interact without authentication? For instance, I would like to enable some kind of SMS-based registration, which means the first request only carry the mobile number and APPCODE without authentication and then the plugin represent this user to signup and send the passcode back via SMS. Is it possible now?
Thanks in advance.
Best regards
Yuexin

**Comment by giastfader** [comment]
The default behavior actually is to accept unauthenticated requests.
Inside the plugin you can switch to the "admin" context and create a new user.
BaasBox cannot send SMS, but this can be done by the plugin caller, or you can even think to use the Box.WS API to call a third-party SMS service.

Please take a look here to know how to create new user inside a plugin:
https://github.com/baasbox/baasbox/wiki/Plugin-Engine#create-a-session-object

**Comment by weahoo** [comment]
Thanks, I noticed the unauthenticated request carried with the X-BB-APPCODE and proper appcode can be handled properly, if not, then error returned with the following message. Is there anyway to react incoming request without such a header? Imaging 3rd party call can simply post request back without adding header features?

`{"result":"error","message":"Missing Session Token, Authorization info and even the AppCode","resource":"/plugin/com.motionext.sms_manager","method":"GET","request_header":{"Connection":["keep-alive"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"Cookie":["wp-settings-1=libraryContent%3Dbrowse%26imgsize%3Dlarge%26posts_list_mode%3Dexcerpt%26editor%3Dtinymce%26wplink%3D1; wp-settings-time-1=1450754825; tour_current_step_0=0; tour_end_0=yes"],"Accept-Language":["en-US,en;q=0.5"],"Accept-Encoding":["gzip, deflate"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"],"Host":["54.178.186.52:9000"]},"API_version":"0.9.4"}`
