### ISSUE TITLE
Rest Api - Query by creation date returns the wrong data

### ISSUE THREAD

**Issue by Alexintosh** [baasbox/baasbox#938]
I'm having a very hard time trying to query some documents by a _creation_date range.

My decoded url looks like this:
`https://urltomyapi/document/collectionname?where=_creation_date >= 2016-01-01T00:00:00+01:00&_creation_date <= 2016-03-16T00:00:00+01:00&orderBy=_creation_date desc"`

I'm not getting any error but the response contains all the documents.
Can somebody help?

**Comment by Alexintosh** [comment]
More accurate title

**Comment by nicom24** [comment]
You should try this:
http://104.155.91.20:443/document/<collection_name>?where=_creation_date.format('yyyy-MM-dd hh:mm:ss') between '2016-04-05 10:00:00' and '2016-04-05 20:00:00'

Further reading:
OrientDB date management http://orientdb.com/docs/2.1/Managing-Dates.html
OrientDB filtering operation (between) http://orientdb.com/docs/2.1/SQL-Where.html

**Comment by nicomon24** [comment]
You should try this:
http://URL/document/COLLECTION_NAME?where=_creation_date.format('yyyy-MM-dd hh:mm:ss') between '2016-04-05 10:00:00' and '2016-04-05 20:00:00'

Further reading:
OrientDB date management http://orientdb.com/docs/2.1/Managing-Dates.html
OrientDB filtering operation (between) http://orientdb.com/docs/2.1/SQL-Where.html

**Comment by Alexintosh** [comment]
Thanks you @nicom24 this really helped, basically can I use any orient db keywords inside the get param ?

**Comment by nicomon24** [comment]
yes @Alexintosh , everything that you put in the params is mapped into an OrientDB query, so you can use every command available (in this case of document GET is a select)
If you use plugins you can also perform direct commands on the DB
Remember also to use single quotes (you missed them in the question)

**Comment by Alexintosh** [comment]
Thanks again.
