### ISSUE TITLE
How do I change the format of the server response in the plugin?

### ISSUE THREAD

**Issue by hunter255** [baasbox/baasbox#941]
Hi! I need to change the format of server response in the plugin, such as the normal string is not in json format. Is it possible standard means? If not, which parts of the source code is necessary to correct for this?

The response I get it now:
`{"result":"ok","data":"39ce91b1","http_code":200}`

The response is that I need to get:
`39ce91b1`

The fact that this answer comes to third-party service, so I can't get it to parse itself, and the service does not accept the answer in this form

I would be grateful for your response.
p.s. English isn’t my first language, so please excuse any mistakes.

**Comment by hunter255** [comment]
I withdraw my question. The problem turned out to solve with the help of a proxy server by changing the response format on it

**Comment by giastfader** [comment]
Great! Can you share some info, please?

**Comment by hunter255** [comment]
I created a PHP script which runs on Apache. And it sent requests to third-party servers. In the script, depending on coming data, redirect the request to the right plugin, then change the answer from the plugin that I needed.

Example php code for the query in the plugin and change the answer from him:

```
<?php
$groupId = $_REQUEST["group_id"];
$myCurl = curl_init();
curl_setopt_array($myCurl, array(
                CURLOPT_URL => "http://localhost:9000/plugin/vkgroup.confirmation?X-BAASBOX-APPCODE=1234567890",
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_POST => true,
                CURLOPT_POSTFIELDS => http_build_query(array("group_id"=>$groupId))
            ));
$response = curl_exec($myCurl);
curl_close($myCurl);
$decoded = json_decode(stripslashes($response), TRUE);
header("Content-type: text/plain; charset=utf-8");
if (is_null($decoded)) {
  exit("bad request");
} else {
  $content = $decoded["data"];
  if (isset($content)) {
      exit($content);
   }
}
?>
```
